[package]
name = "zkp_raffle"
type = "bin"
authors = ["John Heinnickel"]

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
merkle = { tag = "v0.0.2", git = "https://github.com/thermofisher-jch/binary-merkle-noir" }
